# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_auto_20181019_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='Name',
            new_name='name',
        ),
    ]
