# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_auto_20181021_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='health',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='police',
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.TextField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='description',
            field=models.TextField(default='Our neighbourhood!!!'),
        ),
    ]
